export const countriesList = [
    { flag: "🇦🇫", code: "AF", name: "Afghanistan", nameRu: "Афганистан" },
    { flag: "🇦🇽", code: "AX", name: "Åland Islands", nameRu: "Аландские острова" },
    { flag: "🇦🇱", code: "AL", name: "Albania", nameRu: "Албания" },
    { flag: "🇩🇿", code: "DZ", name: "Algeria", nameRu: "Алжир" },
    { flag: "🇦🇸", code: "AS", name: "American Samoa", nameRu: "Американское Самоа" },
    { flag: "🇦🇩", code: "AD", name: "Andorra", nameRu: "Андорра" },
    { flag: "🇦🇴", code: "AO", name: "Angola", nameRu: "Ангола" },
    { flag: "🇦🇮", code: "AI", name: "Anguilla", nameRu: "Ангилья" },
    { flag: "🇦🇶", code: "AQ", name: "Antarctica", nameRu: "Антарктида" },
    { flag: "🇦🇬", code: "AG", name: "Antigua and Barbuda", nameRu: "Антигуа и Барбуда" },
    { flag: "🇦🇷", code: "AR", name: "Argentina", nameRu: "Аргентина" },
    { flag: "🇦🇲", code: "AM", name: "Armenia", nameRu: "Армения" },
    { flag: "🇦🇼", code: "AW", name: "Aruba", nameRu: "Аруба" },
    { flag: "🇦🇺", code: "AU", name: "Australia", nameRu: "Австралия" },
    { flag: "🇦🇹", code: "AT", name: "Austria", nameRu: "Австрия" },
    { flag: "🇦🇿", code: "AZ", name: "Azerbaijan", nameRu: "Азербайджан" },
    { flag: "🇧🇸", code: "BS", name: "Bahamas", nameRu: "Багамы" },
    { flag: "🇧🇭", code: "BH", name: "Bahrain", nameRu: "Бахрейн" },
    { flag: "🇧🇩", code: "BD", name: "Bangladesh", nameRu: "Бангладеш" },
    { flag: "🇧🇧", code: "BB", name: "Barbados", nameRu: "Барбадос" },
    { flag: "🇧🇾", code: "BY", name: "Belarus", nameRu: "Беларусь" },
    { flag: "🇧🇪", code: "BE", name: "Belgium", nameRu: "Бельгия" },
    { flag: "🇧🇿", code: "BZ", name: "Belize", nameRu: "Белиз" },
    { flag: "🇧🇯", code: "BJ", name: "Benin", nameRu: "Бенин" },
    { flag: "🇧🇲", code: "BM", name: "Bermuda", nameRu: "Бермуды" },
    { flag: "🇧🇹", code: "BT", name: "Bhutan", nameRu: "Бутан" },
    { flag: "🇧🇴", code: "BO", name: "Bolivia", nameRu: "Боливия" },
    { flag: "🇧🇶", code: "BQ", name: "Bonaire, Sint Eustatius and Saba", nameRu: "Бонайре, Синт-Эстатиус и Саба" },
    { flag: "🇧🇦", code: "BA", name: "Bosnia and Herzegovina", nameRu: "Босния и Герцеговина" },
    { flag: "🇧🇼", code: "BW", name: "Botswana", nameRu: "Ботсвана" },
    { flag: "🇧🇻", code: "BV", name: "Bouvet Island", nameRu: "Остров Буве" },
    { flag: "🇧🇷", code: "BR", name: "Brazil", nameRu: "Бразилия" },
    { flag: "🇮🇴", code: "IO", name: "British Indian Ocean Territory", nameRu: "Британская территория Индийского океана" },
    { flag: "🇧🇳", code: "BN", name: "Brunei Darussalam", nameRu: "Бруней" },
    { flag: "🇧🇬", code: "BG", name: "Bulgaria", nameRu: "Болгария" },
    { flag: "🇧🇫", code: "BF", name: "Burkina Faso", nameRu: "Буркина-Фасо" },
    { flag: "🇧🇮", code: "BI", name: "Burundi", nameRu: "Бурунди" },
    { flag: "🇨🇻", code: "CV", name: "Cabo Verde", nameRu: "Кабо-Верде" },
    { flag: "🇰🇭", code: "KH", name: "Cambodia", nameRu: "Камбоджа" },
    { flag: "🇨🇲", code: "CM", name: "Cameroon", nameRu: "Камерун" },
    { flag: "🇨🇦", code: "CA", name: "Canada", nameRu: "Канада" },
    { flag: "🇰🇾", code: "KY", name: "Cayman Islands", nameRu: "Каймановы острова" },
    { flag: "🇨🇫", code: "CF", name: "Central African Republic", nameRu: "Центральноафриканская Республика" },
    { flag: "🇹🇩", code: "TD", name: "Chad", nameRu: "Чад" },
    { flag: "🇨🇱", code: "CL", name: "Chile", nameRu: "Чили" },
    { flag: "🇨🇳", code: "CN", name: "China", nameRu: "Китай" },
    { flag: "🇨🇽", code: "CX", name: "Christmas Island", nameRu: "Остров Рождества" },
    { flag: "🇨🇨", code: "CC", name: "Cocos (Keeling) Islands", nameRu: "Кокосовые острова" },
    { flag: "🇨🇴", code: "CO", name: "Colombia", nameRu: "Колумбия" },
    { flag: "🇰🇲", code: "KM", name: "Comoros", nameRu: "Коморы" },
    { flag: "🇨🇬", code: "CG", name: "Congo", nameRu: "Конго" },
    { flag: "🇨🇩", code: "CD", name: "Congo, Democratic Republic of the", nameRu: "Демократическая Республика Конго" },
    { flag: "🇨🇰", code: "CK", name: "Cook Islands", nameRu: "Острова Кука" },
    { flag: "🇨🇷", code: "CR", name: "Costa Rica", nameRu: "Коста-Рика" },
    { flag: "🇨🇮", code: "CI", name: "Côte d'Ivoire", nameRu: "Кот-д’Ивуар" },
    { flag: "🇭🇷", code: "HR", name: "Croatia", nameRu: "Хорватия" },
    { flag: "🇨🇺", code: "CU", name: "Cuba", nameRu: "Куба" },
    { flag: "🇨🇼", code: "CW", name: "Curaçao", nameRu: "Кюрасао" },
    { flag: "🇨🇾", code: "CY", name: "Cyprus", nameRu: "Кипр" },
    { flag: "🇨🇿", code: "CZ", name: "Czech Republic", nameRu: "Чехия" },
    { flag: "🇩🇰", code: "DK", name: "Denmark", nameRu: "Дания" },
    { flag: "🇩🇯", code: "DJ", name: "Djibouti", nameRu: "Джибути" },
    { flag: "🇩🇲", code: "DM", name: "Dominica", nameRu: "Доминика" },
    { flag: "🇩🇴", code: "DO", name: "Dominican Republic", nameRu: "Доминиканская Республика" },
    { flag: "🇪🇨", code: "EC", name: "Ecuador", nameRu: "Эквадор" },
    { flag: "🇪🇬", code: "EG", name: "Egypt", nameRu: "Египет" },
    { flag: "🇸🇻", code: "SV", name: "El Salvador", nameRu: "Сальвадор" },
    { flag: "🇬🇶", code: "GQ", name: "Equatorial Guinea", nameRu: "Экваториальная Гвинея" },
    { flag: "🇪🇷", code: "ER", name: "Eritrea", nameRu: "Эритрея" },
    { flag: "🇪🇪", code: "EE", name: "Estonia", nameRu: "Эстония" },
    { flag: "🇸🇿", code: "SZ", name: "Eswatini", nameRu: "Эсватини" },
    { flag: "🇪🇹", code: "ET", name: "Ethiopia", nameRu: "Эфиопия" },
    { flag: "🇫🇰", code: "FK", name: "Falkland Islands", nameRu: "Фолклендские острова" },
    { flag: "🇫🇴", code: "FO", name: "Faroe Islands", nameRu: "Фарерские острова" },
    { flag: "🇫🇯", code: "FJ", name: "Fiji", nameRu: "Фиджи" },
    { flag: "🇫🇮", code: "FI", name: "Finland", nameRu: "Финляндия" },
    { flag: "🇫🇷", code: "FR", name: "France", nameRu: "Франция" },
    { flag: "🇬🇫", code: "GF", name: "French Guiana", nameRu: "Французская Гвиана" },
    { flag: "🇵🇫", code: "PF", name: "French Polynesia", nameRu: "Французская Полинезия" },
    { flag: "🇹🇫", code: "TF", name: "French Southern Territories", nameRu: "Французские Южные территории" },
    { flag: "🇬🇦", code: "GA", name: "Gabon", nameRu: "Габон" },
    { flag: "🇬🇲", code: "GM", name: "Gambia", nameRu: "Гамбия" },
    { flag: "🇬🇪", code: "GE", name: "Georgia", nameRu: "Грузия" },
    { flag: "🇩🇪", code: "DE", name: "Germany", nameRu: "Германия" },
    { flag: "🇬🇭", code: "GH", name: "Ghana", nameRu: "Гана" },
    { flag: "🇬🇮", code: "GI", name: "Gibraltar", nameRu: "Гибралтар" },
    { flag: "🇬🇷", code: "GR", name: "Greece", nameRu: "Греция" },
    { flag: "🇬🇱", code: "GL", name: "Greenland", nameRu: "Гренландия" },
    { flag: "🇬🇩", code: "GD", name: "Grenada", nameRu: "Гренада" },
    { flag: "🇬🇵", code: "GP", name: "Guadeloupe", nameRu: "Гваделупа" },
    { flag: "🇬🇺", code: "GU", name: "Guam", nameRu: "Гуам" },
    { flag: "🇬🇹", code: "GT", name: "Guatemala", nameRu: "Гватемала" },
    { flag: "🇬🇬", code: "GG", name: "Guernsey", nameRu: "Гернси" },
    { flag: "🇬🇳", code: "GN", name: "Guinea", nameRu: "Гвинея" },
    { flag: "🇬🇼", code: "GW", name: "Guinea-Bissau", nameRu: "Гвинея-Бисау" },
    { flag: "🇬🇾", code: "GY", name: "Guyana", nameRu: "Гайана" },
    { flag: "🇭🇹", code: "HT", name: "Haiti", nameRu: "Гаити" },
    { flag: "🇭🇲", code: "HM", name: "Heard Island and McDonald Islands", nameRu: "Остров Херд и острова Макдональд" },
    { flag: "🇻🇦", code: "VA", name: "Holy See", nameRu: "Ватикан" },
    { flag: "🇭🇳", code: "HN", name: "Honduras", nameRu: "Гондурас" },
    { flag: "🇭🇰", code: "HK", name: "Hong Kong", nameRu: "Гонконг" },
    { flag: "🇭🇺", code: "HU", name: "Hungary", nameRu: "Венгрия" },
    { flag: "🇮🇸", code: "IS", name: "Iceland", nameRu: "Исландия" },
    { flag: "🇮🇳", code: "IN", name: "India", nameRu: "Индия" },
    { flag: "🇮🇩", code: "ID", name: "Indonesia", nameRu: "Индонезия" },
    { flag: "🇮🇷", code: "IR", name: "Iran", nameRu: "Иран" },
    { flag: "🇮🇶", code: "IQ", name: "Iraq", nameRu: "Ирак" },
    { flag: "🇮🇪", code: "IE", name: "Ireland", nameRu: "Ирландия" },
    { flag: "🇮🇲", code: "IM", name: "Isle of Man", nameRu: "Остров Мэн" },
    { flag: "🇮🇱", code: "IL", name: "Israel", nameRu: "Израиль" },
    { flag: "🇮🇹", code: "IT", name: "Italy", nameRu: "Италия" },
    { flag: "🇯🇲", code: "JM", name: "Jamaica", nameRu: "Ямайка" },
    { flag: "🇯🇵", code: "JP", name: "Japan", nameRu: "Япония" },
    { flag: "🇯🇪", code: "JE", name: "Jersey", nameRu: "Джерси" },
    { flag: "🇯🇴", code: "JO", name: "Jordan", nameRu: "Иордания" },
    { flag: "🇰🇿", code: "KZ", name: "Kazakhstan", nameRu: "Казахстан" },
    { flag: "🇰🇪", code: "KE", name: "Kenya", nameRu: "Кения" },
    { flag: "🇰🇮", code: "KI", name: "Kiribati", nameRu: "Кирибати" },
    { flag: "🇰🇵", code: "KP", name: "Korea, Democratic People's Republic of", nameRu: "КНДР" },
    { flag: "🇰🇷", code: "KR", name: "Korea, Republic of", nameRu: "Южная Корея" },
    { flag: "🇰🇼", code: "KW", name: "Kuwait", nameRu: "Кувейт" },
    { flag: "🇰🇬", code: "KG", name: "Kyrgyzstan", nameRu: "Кыргызстан" },
    { flag: "🇱🇦", code: "LA", name: "Lao People's Democratic Republic", nameRu: "Лаос" },
    { flag: "🇱🇻", code: "LV", name: "Latvia", nameRu: "Латвия" },
    { flag: "🇱🇧", code: "LB", name: "Lebanon", nameRu: "Ливан" },
    { flag: "🇱🇸", code: "LS", name: "Lesotho", nameRu: "Лесото" },
    { flag: "🇱🇷", code: "LR", name: "Liberia", nameRu: "Либерия" },
    { flag: "🇱🇾", code: "LY", name: "Libya", nameRu: "Ливия" },
    { flag: "🇱🇮", code: "LI", name: "Liechtenstein", nameRu: "Лихтенштейн" },
    { flag: "🇱🇹", code: "LT", name: "Lithuania", nameRu: "Литва" },
    { flag: "🇱🇺", code: "LU", name: "Luxembourg", nameRu: "Люксембург" },
    { flag: "🇲🇴", code: "MO", name: "Macao", nameRu: "Макао" },
    { flag: "🇲🇬", code: "MG", name: "Madagascar", nameRu: "Мадагаскар" },
    { flag: "🇲🇼", code: "MW", name: "Malawi", nameRu: "Малави" },
    { flag: "🇲🇾", code: "MY", name: "Malaysia", nameRu: "Малайзия" },
    { flag: "🇲🇻", code: "MV", name: "Maldives", nameRu: "Мальдивы" },
    { flag: "🇲🇱", code: "ML", name: "Mali", nameRu: "Мали" },
    { flag: "🇲🇹", code: "MT", name: "Malta", nameRu: "Мальта" },
    { flag: "🇲🇭", code: "MH", name: "Marshall Islands", nameRu: "Маршалловы Острова" },
    { flag: "🇲🇶", code: "MQ", name: "Martinique", nameRu: "Мартиника" },
    { flag: "🇲🇷", code: "MR", name: "Mauritania", nameRu: "Мавритания" },
    { flag: "🇲🇺", code: "MU", name: "Mauritius", nameRu: "Маврикий" },
    { flag: "🇾🇹", code: "YT", name: "Mayotte", nameRu: "Майотта" },
    { flag: "🇲🇽", code: "MX", name: "Mexico", nameRu: "Мексика" },
    { flag: "🇫🇲", code: "FM", name: "Micronesia", nameRu: "Микронезия" },
    { flag: "🇲🇩", code: "MD", name: "Moldova", nameRu: "Молдова" },
    { flag: "🇲🇨", code: "MC", name: "Monaco", nameRu: "Монако" },
    { flag: "🇲🇳", code: "MN", name: "Mongolia", nameRu: "Монголия" },
    { flag: "🇲🇪", code: "ME", name: "Montenegro", nameRu: "Черногория" },
    { flag: "🇲🇸", code: "MS", name: "Montserrat", nameRu: "Монтсеррат" },
    { flag: "🇲🇦", code: "MA", name: "Morocco", nameRu: "Марокко" },
    { flag: "🇲🇿", code: "MZ", name: "Mozambique", nameRu: "Мозамбик" },
    { flag: "🇲🇲", code: "MM", name: "Myanmar", nameRu: "Мьянма" },
    { flag: "🇳🇦", code: "NA", name: "Namibia", nameRu: "Намибия" },
    { flag: "🇳🇷", code: "NR", name: "Nauru", nameRu: "Науру" },
    { flag: "🇳🇵", code: "NP", name: "Nepal", nameRu: "Непал" },
    { flag: "🇳🇱", code: "NL", name: "Netherlands", nameRu: "Нидерланды" },
    { flag: "🇳🇨", code: "NC", name: "New Caledonia", nameRu: "Новая Каледония" },
    { flag: "🇳🇿", code: "NZ", name: "New Zealand", nameRu: "Новая Зеландия" },
    { flag: "🇳🇮", code: "NI", name: "Nicaragua", nameRu: "Никарагуа" },
    { flag: "🇳🇪", code: "NE", name: "Niger", nameRu: "Нигер" },
    { flag: "🇳🇬", code: "NG", name: "Nigeria", nameRu: "Нигерия" },
    { flag: "🇳🇺", code: "NU", name: "Niue", nameRu: "Ниуэ" },
    { flag: "🇳🇫", code: "NF", name: "Norfolk Island", nameRu: "Остров Норфолк" },
    { flag: "🇲🇵", code: "MP", name: "Northern Mariana Islands", nameRu: "Северные Марианские острова" },
    { flag: "🇳🇴", code: "NO", name: "Norway", nameRu: "Норвегия" },
    { flag: "🇴🇲", code: "OM", name: "Oman", nameRu: "Оман" },
    { flag: "🇵🇰", code: "PK", name: "Pakistan", nameRu: "Пакистан" },
    { flag: "🇵🇼", code: "PW", name: "Palau", nameRu: "Палау" },
    { flag: "🇵🇸", code: "PS", name: "Palestine", nameRu: "Палестина" },
    { flag: "🇵🇦", code: "PA", name: "Panama", nameRu: "Панама" },
    { flag: "🇵🇬", code: "PG", name: "Papua New Guinea", nameRu: "Папуа — Новая Гвинея" },
    { flag: "🇵🇾", code: "PY", name: "Paraguay", nameRu: "Парагвай" },
    { flag: "🇵🇪", code: "PE", name: "Peru", nameRu: "Перу" },
    { flag: "🇵🇭", code: "PH", name: "Philippines", nameRu: "Филиппины" },
    { flag: "🇵🇳", code: "PN", name: "Pitcairn", nameRu: "Питкэрн" },
    { flag: "🇵🇱", code: "PL", name: "Poland", nameRu: "Польша" },
    { flag: "🇵🇹", code: "PT", name: "Portugal", nameRu: "Португалия" },
    { flag: "🇵🇷", code: "PR", name: "Puerto Rico", nameRu: "Пуэрто-Рико" },
    { flag: "🇶🇦", code: "QA", name: "Qatar", nameRu: "Катар" },
    { flag: "🇷🇪", code: "RE", name: "Réunion", nameRu: "Реюньон" },
    { flag: "🇷🇴", code: "RO", name: "Romania", nameRu: "Румыния" },
    { flag: "🇷🇺", code: "RU", name: "Russia", nameRu: "Россия" },
    { flag: "🇷🇼", code: "RW", name: "Rwanda", nameRu: "Руанда" },
    { flag: "🇧🇱", code: "BL", name: "Saint Barthélemy", nameRu: "Сен-Бартелеми" },
    { flag: "🇸🇭", code: "SH", name: "Saint Helena", nameRu: "Святая Елена" },
    { flag: "🇰🇳", code: "KN", name: "Saint Kitts and Nevis", nameRu: "Сент-Китс и Невис" },
    { flag: "🇱🇨", code: "LC", name: "Saint Lucia", nameRu: "Сент-Люсия" },
    { flag: "🇲🇫", code: "MF", name: "Saint Martin", nameRu: "Сен-Мартен" },
    { flag: "🇵🇲", code: "PM", name: "Saint Pierre and Miquelon", nameRu: "Сен-Пьер и Микелон" },
    { flag: "🇻🇨", code: "VC", name: "Saint Vincent and the Grenadines", nameRu: "Сент-Винсент и Гренадины" },
    { flag: "🇼🇸", code: "WS", name: "Samoa", nameRu: "Самоа" },
    { flag: "🇸🇲", code: "SM", name: "San Marino", nameRu: "Сан-Марино" },
    { flag: "🇸🇹", code: "ST", name: "Sao Tome and Principe", nameRu: "Сан-Томе и Принсипи" },
    { flag: "🇸🇦", code: "SA", name: "Saudi Arabia", nameRu: "Саудовская Аравия" },
    { flag: "🇸🇳", code: "SN", name: "Senegal", nameRu: "Сенегал" },
    { flag: "🇷🇸", code: "RS", name: "Serbia", nameRu: "Сербия" },
    { flag: "🇸🇨", code: "SC", name: "Seychelles", nameRu: "Сейшельские Острова" },
    { flag: "🇸🇱", code: "SL", name: "Sierra Leone", nameRu: "Сьерра-Леоне" },
    { flag: "🇸🇬", code: "SG", name: "Singapore", nameRu: "Сингапур" },
    { flag: "🇸🇽", code: "SX", name: "Sint Maarten", nameRu: "Синт-Мартен" },
    { flag: "🇸🇰", code: "SK", name: "Slovakia", nameRu: "Словакия" },
    { flag: "🇸🇮", code: "SI", name: "Slovenia", nameRu: "Словения" },
    { flag: "🇸🇧", code: "SB", name: "Solomon Islands", nameRu: "Соломоновы Острова" },
    { flag: "🇸🇴", code: "SO", name: "Somalia", nameRu: "Сомали" },
    { flag: "🇿🇦", code: "ZA", name: "South Africa", nameRu: "Южная Африка" },
    { flag: "🇬🇸", code: "GS", name: "South Georgia and the South Sandwich Islands", nameRu: "Южная Георгия и Южные Сандвичевы острова" },
    { flag: "🇸🇸", code: "SS", name: "South Sudan", nameRu: "Южный Судан" },
    { flag: "🇪🇸", code: "ES", name: "Spain", nameRu: "Испания" },
    { flag: "🇱🇰", code: "LK", name: "Sri Lanka", nameRu: "Шри-Ланка" },
    { flag: "🇸🇩", code: "SD", name: "Sudan", nameRu: "Судан" },
    { flag: "🇸🇷", code: "SR", name: "Suriname", nameRu: "Суринам" },
    { flag: "🇸🇯", code: "SJ", name: "Svalbard and Jan Mayen", nameRu: "Шпицберген и Ян-Майен" },
    { flag: "🇸🇪", code: "SE", name: "Sweden", nameRu: "Швеция" },
    { flag: "🇨🇭", code: "CH", name: "Switzerland", nameRu: "Швейцария" },
    { flag: "🇸🇾", code: "SY", name: "Syria", nameRu: "Сирия" },
    { flag: "🇹🇼", code: "TW", name: "Taiwan", nameRu: "Тайвань" },
    { flag: "🇹🇯", code: "TJ", name: "Tajikistan", nameRu: "Таджикистан" },
    { flag: "🇹🇿", code: "TZ", name: "Tanzania", nameRu: "Танзания" },
    { flag: "🇹🇭", code: "TH", name: "Thailand", nameRu: "Таиланд" },
    { flag: "🇹🇱", code: "TL", name: "Timor-Leste", nameRu: "Восточный Тимор" },
    { flag: "🇹🇬", code: "TG", name: "Togo", nameRu: "Того" },
    { flag: "🇹🇰", code: "TK", name: "Tokelau", nameRu: "Токелау" },
    { flag: "🇹🇴", code: "TO", name: "Tonga", nameRu: "Тонга" },
    { flag: "🇹🇹", code: "TT", name: "Trinidad and Tobago", nameRu: "Тринидад и Тобаго" },
    { flag: "🇹🇳", code: "TN", name: "Tunisia", nameRu: "Тунис" },
    { flag: "🇹🇷", code: "TR", name: "Turkey", nameRu: "Турция" },
    { flag: "🇹🇲", code: "TM", name: "Turkmenistan", nameRu: "Туркменистан" },
    { flag: "🇹🇨", code: "TC", name: "Turks and Caicos Islands", nameRu: "Теркс и Кайкос" },
    { flag: "🇹🇻", code: "TV", name: "Tuvalu", nameRu: "Тувалу" },
    { flag: "🇺🇬", code: "UG", name: "Uganda", nameRu: "Уганда" },
    { flag: "🇺🇦", code: "UA", name: "Ukraine", nameRu: "Украина" },
    { flag: "🇦🇪", code: "AE", name: "United Arab Emirates", nameRu: "Объединённые Арабские Эмираты" },
    { flag: "🇬🇧", code: "GB", name: "United Kingdom", nameRu: "Великобритания" },
    { flag: "🇺🇸", code: "US", name: "United States", nameRu: "Соединённые Штаты" },
    { flag: "🇺🇲", code: "UM", name: "United States Minor Outlying Islands", nameRu: "Малые отдалённые острова США" },
    { flag: "🇺🇾", code: "UY", name: "Uruguay", nameRu: "Уругвай" },
    { flag: "🇺🇿", code: "UZ", name: "Uzbekistan", nameRu: "Узбекистан" },
    { flag: "🇻🇺", code: "VU", name: "Vanuatu", nameRu: "Вануату" },
    { flag: "🇻🇪", code: "VE", name: "Venezuela", nameRu: "Венесуэла" },
    { flag: "🇻🇳", code: "VN", name: "Vietnam", nameRu: "Вьетнам" },
    { flag: "🇻🇬", code: "VG", name: "Virgin Islands (British)", nameRu: "Британские Виргинские острова" },
    { flag: "🇻🇮", code: "VI", name: "Virgin Islands (U.S.)", nameRu: "Виргинские острова (США)" },
    { flag: "🇼🇫", code: "WF", name: "Wallis and Futuna", nameRu: "Уоллис и Футуна" },
    { flag: "🇪🇭", code: "EH", name: "Western Sahara", nameRu: "Западная Сахара" },
    { flag: "🇾🇪", code: "YE", name: "Yemen", nameRu: "Йемен" },
    { flag: "🇿🇲", code: "ZM", name: "Zambia", nameRu: "Замбия" },
    { flag: "🇿🇼", code: "ZW", name: "Zimbabwe", nameRu: "Зимбабве" }
];